//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingAndFreezerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankFreezer
    {
        public int id { get; set; }
        public Nullable<decimal> CurrentPrices { get; set; }
        public Nullable<int> FrID { get; set; }
    
        public virtual Fridage Fridage { get; set; }
    }
}
