//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingAndFreezerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Number { get; set; }
        public Nullable<decimal> PricePerOneSm { get; set; }
        public Nullable<decimal> PricePerOneLa { get; set; }
        public Nullable<decimal> NewPricePerOneLa { get; set; }
        public Nullable<decimal> NewPricePerOneSm { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Size { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public Nullable<decimal> Change { get; set; }
        public string Section { get; set; }
        public Nullable<int> Cat_id { get; set; }
        public int FrID { get; set; }
        public Nullable<int> billID { get; set; }
    
        public virtual FreezerCeteogry FreezerCeteogry { get; set; }
        public virtual Fridage Fridage { get; set; }
    }
}
