//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingAndFreezerApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BuildingandFreezerEntities : DbContext
    {
        public BuildingandFreezerEntities()
            : base("name=BuildingandFreezerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<BankFreezer> BankFreezers { get; set; }
        public virtual DbSet<Building> Buildings { get; set; }
        public virtual DbSet<BuildingEmployee> BuildingEmployees { get; set; }
        public virtual DbSet<BuildingMatrial> BuildingMatrials { get; set; }
        public virtual DbSet<ClientReserve> ClientReserves { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Employess> Employesses { get; set; }
        public virtual DbSet<FreezerCeteogry> FreezerCeteogries { get; set; }
        public virtual DbSet<Fridage> Fridages { get; set; }
        public virtual DbSet<Matriel> Matriels { get; set; }
        public virtual DbSet<NonWork> NonWorks { get; set; }
        public virtual DbSet<NonWorksTable> NonWorksTables { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<period> periods { get; set; }
        public virtual DbSet<Reserve> Reserves { get; set; }
        public virtual DbSet<Trader> Traders { get; set; }
        public virtual DbSet<BankBuilding> BankBuildings { get; set; }
    }
}
