//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingAndFreezerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonWork
    {
        public int id { get; set; }
        public Nullable<int> NonId { get; set; }
        public string Det { get; set; }
        public Nullable<decimal> Prices { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> BuildID { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual NonWorksTable NonWorksTable { get; set; }
    }
}
