//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingAndFreezerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserve
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reserve()
        {
            this.ClientReserves = new HashSet<ClientReserve>();
        }
    
        public int id { get; set; }
        public Nullable<int> BuildID { get; set; }
        public Nullable<int> FlatNumber { get; set; }
        public string ClientName { get; set; }
        public string ClientAddress { get; set; }
        public string ClientPhoto { get; set; }
        public Nullable<decimal> RePrices { get; set; }
        public Nullable<decimal> CashPrices { get; set; }
        public Nullable<decimal> Comission { get; set; }
        public Nullable<decimal> ChangePrices { get; set; }
        public Nullable<int> NumPrem { get; set; }
        public Nullable<System.DateTime> DateFirstPrem { get; set; }
        public string Photo { get; set; }
        public Nullable<int> Period { get; set; }
    
        public virtual Building Building { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientReserve> ClientReserves { get; set; }
    }
}
